### ISSUE TITLE
Why is static compilation impossible?

### ISSUE THREAD

**Issue by Techno-Fox** [tazz4843/coqui-stt#12]
I've read in other issues that you tried to get static compilation, but in your read me you just say "static compilation is impossible". Why is it impossible?

**Comment by tazz4843** [comment]
Static compilation brings a lot of issues with licensing, and Coqui doesn't offer a build that can be statically linked as far as I know, because of these licensing issues.

**Comment by tazz4843** [comment]
Gonna close this since it's been almost a month now. If you need more help, feel free to reopen.
