### ISSUE TITLE
document install process

### ISSUE THREAD

**Issue by droundy** [tazz4843/coqui-stt#5]
It looks like `libcoqui-sys` does not automatically grab the C library, so it would be nice to document in the `README.md` how and where to get it, and which version this will work with.

**Comment by droundy** [comment]
I managed the install (suboptimally) by unzipping the released [libstt.tflite.Linux.zip](https://github.com/coqui-ai/STT/releases/download/v1.3.0/libstt.tflite.Linux.zip) into `/usr/local/lib` and then running `ldconfig`.  It would be nice to be able to install without being root.  And even nicer for this to be automatic, and involve a statically linked library.

**Comment by tazz4843** [comment]
I'll put some time into this later tonight, and see if I can pull off static linking in the current directory. Sorry for not getting back to you here earlier, GitHub notifications seem to have broken.

**Comment by tazz4843** [comment]
Closed in b5a1889b06ea9d418fb12cdf6dc9c10381cf33b5.

**Comment by droundy** [comment]
Thanks!
